version: '3.8'
services:
    ms-sql-server:
        image: mcr.microsoft.com/azure-sql-edge
        environment: 
            ACCEPT_EULA: "1"
            MSSQL_SA_PASSWORD: "MinApiPass1"
            MSSQL_PID: "Developer"
            MSSQL_USER: "SA"
        ports:
            - "1433:1433"
    azurite-blob-storage:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
    minimal-api:
        build:
            context: .
        ports:
            - "4040:4040"
      
    





            

            
  