@Alex.MinimalApi.Service_HostAddress = http://localhost:5058

///EMPLOYEE -----------------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/Employee
Content-Type: application/json

{
  "firstname": "Gerard",
  "lastname": "Tierdrop",
  "age": 12,
  "taxFile": {
      "alias": "GT tax file",
      "taxFileRecords": [
      {
        "financialYear": 2021,
        "amountPaid": 5000,
        "amountClaimed": 132
      },
      {
        "financialYear": 1999,
        "amountPaid": 233,
        "amountClaimed": 111
      }
      ]
  }
}

###

PUT {{Alex.MinimalApi.Service_HostAddress}}/Employee/1004
Content-Type: application/json

{
  "Id": 1004,
  "firstname": "Gerardx",
  "lastname": "Tierdrop",
  "age": 12,
  "taxFile": {
      "Id": 1007,
      "alias": "GT tax filexx",
      "EmployeeId": 1004,
      "taxFileRecords": [
      {
        "Id": 1009,
        "financialYear": 1111,
        "amountPaid": 50,
        "amountClaimed": 50,
        "TaxFileId": 1007
      },
      {
        "financialYear": 2222,
        "amountPaid": 12,
        "amountClaimed": 12,
        "TaxFileId": 1007
      }
      
      ]
  }
}

###

GET {{Alex.MinimalApi.Service_HostAddress}}/Employee
###
GET {{Alex.MinimalApi.Service_HostAddress}}/Employee/2010

###
DELETE {{Alex.MinimalApi.Service_HostAddress}}/Employee/2006
###

///NOTIFICATION ---------------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/Notification
Content-Type: application/json

{
  "message" : "This is a message"
}

###
GET {{Alex.MinimalApi.Service_HostAddress}}/Notification
###
GET {{Alex.MinimalApi.Service_HostAddress}}/Notification/1

###

///PUBLIC DOCUMENT -----------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/PublicDocument
// *** PLEASE USE SWAGGER UI TO SAMPLE POST CONTENT ***