@Alex.MinimalApi.Service_HostAddress = http://localhost:5058

///EMPLOYEE -----------------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/Employee
Content-Type: application/json

{
  "firstname": "Gerard",
  "lastname": "Tierdrop",
  "age": 12,
  "taxFile": {
      "alias": "GT tax file",
      "taxFileRecords": [
      {
        "financialYear": 2021,
        "amountPaid": 5000,
        "amountClaimed": 132
      }
      ]
  }
}

###

PUT {{Alex.MinimalApi.Service_HostAddress}}/Employee/2
Content-Type: application/json

{
  "Id": 2,
  "firstname": "Gerardx",
  "lastname": "Tierdrop",
  "age": 12,
  "taxFile": {
      "Id": 5,
      "alias": "GT tax filexx",
      "taxFileRecords": [
      {
        "Id": 1,
        "financialYear": 2000,
        "amountPaid": 3,
        "amountClaimed": 4
      },
      {
        "Id": 2,
        "financialYear": 1,
        "amountPaid": 1,
        "amountClaimed": 1
      }
      ]
  }
}

###

GET {{Alex.MinimalApi.Service_HostAddress}}/Employee
###
GET {{Alex.MinimalApi.Service_HostAddress}}/Employee/1
###

///NOTIFICATION ---------------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/Notification
Content-Type: application/json

{
  "message" : "This is a message"
}

###
GET {{Alex.MinimalApi.Service_HostAddress}}/Notification
###
GET {{Alex.MinimalApi.Service_HostAddress}}/Notification/1

###

///PUBLIC DOCUMENT -----------------------------------
POST {{Alex.MinimalApi.Service_HostAddress}}/PublicDocument
// *** PLEASE USE SWAGGER UI TO SAMPLE POST CONTENT ***